[package]
name = "database-layer"
version = "1.0.0"
edition = "2021"


[dependencies]

# these are our picks for the project technologies

sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" ] }
async-trait = "0.1"
chrono = "0.4"
anyhow = "1.0"
